// Generated by gencpp from file drone_sensor/StereoCompressedImage.msg
// DO NOT EDIT!


#ifndef DRONE_SENSOR_MESSAGE_STEREOCOMPRESSEDIMAGE_H
#define DRONE_SENSOR_MESSAGE_STEREOCOMPRESSEDIMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/CompressedImage.h>
#include <sensor_msgs/CompressedImage.h>

namespace drone_sensor
{
template <class ContainerAllocator>
struct StereoCompressedImage_
{
  typedef StereoCompressedImage_<ContainerAllocator> Type;

  StereoCompressedImage_()
    : img_l()
    , img_r()  {
    }
  StereoCompressedImage_(const ContainerAllocator& _alloc)
    : img_l(_alloc)
    , img_r(_alloc)  {
    }



   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _img_l_type;
  _img_l_type img_l;

   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _img_r_type;
  _img_r_type img_r;




  typedef boost::shared_ptr< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> const> ConstPtr;

}; // struct StereoCompressedImage_

typedef ::drone_sensor::StereoCompressedImage_<std::allocator<void> > StereoCompressedImage;

typedef boost::shared_ptr< ::drone_sensor::StereoCompressedImage > StereoCompressedImagePtr;
typedef boost::shared_ptr< ::drone_sensor::StereoCompressedImage const> StereoCompressedImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_sensor::StereoCompressedImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drone_sensor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'drone_sensor': ['/home/mrh/catkin_ws/src/drone_sensor/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ceed374241f8976da987d11a5d3c17ef";
  }

  static const char* value(const ::drone_sensor::StereoCompressedImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xceed374241f8976dULL;
  static const uint64_t static_value2 = 0xa987d11a5d3c17efULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_sensor/StereoCompressedImage";
  }

  static const char* value(const ::drone_sensor::StereoCompressedImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/CompressedImage  img_l\n\
sensor_msgs/CompressedImage  img_r\n\
\n\
================================================================================\n\
MSG: sensor_msgs/CompressedImage\n\
# This message contains a compressed image\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
\n\
string format        # Specifies the format of the data\n\
                     #   Acceptable values:\n\
                     #     jpeg, png\n\
uint8[] data         # Compressed image buffer\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::drone_sensor::StereoCompressedImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.img_l);
      stream.next(m.img_r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct StereoCompressedImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_sensor::StereoCompressedImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_sensor::StereoCompressedImage_<ContainerAllocator>& v)
  {
    s << indent << "img_l: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.img_l);
    s << indent << "img_r: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.img_r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_SENSOR_MESSAGE_STEREOCOMPRESSEDIMAGE_H
